# Generated by Django 4.2.4 on 2023-08-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ItemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_image', models.URLField()),
                ('item_name', models.CharField(max_length=50)),
                ('item_color', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=0, max_digits=9)),
            ],
        ),
    ]
