# Generated by Django 4.2.4 on 2023-08-30 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iteminfo',
            old_name='item_color',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='iteminfo',
            old_name='item_name',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='iteminfo',
            old_name='item_image',
            new_name='image',
        ),
    ]
