# Generated by Django 4.2.4 on 2023-09-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0005_rename_color_iteminfo_item_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
